### ISSUE TITLE
Infografia  de caliadad sofware unidad 4

### ISSUE THREAD

**Issue by luzm23** [SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-luzm23#1]
[Infografia  Calidad  y diferentes tipos de pruebas unidad 4.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-luzm23/files/15472941/Infografia.Calidad.y.diferentes.tipos.de.pruebas.unidad.4.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado Calificacion  20
