### ISSUE TITLE
PRACTICA 7 PRUEBAS UNITARIAS

### ISSUE THREAD

**Issue by luzm23** [SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-luzm23#2]
[PRACTRICA.7-PRUEBAS.UNITARIAS.pdf](https://github.com/user-attachments/files/15507016/PRACTRICA.7-PRUEBAS.UNITARIAS.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
